spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    cluster:
      nodes:
       - 10.112.65.77:7000
       - 10.112.65.77:7001


mybatis:
  configuration:
    map-underscore-to-camel-case: true



